### ISSUE TITLE
Youtube 720p60 or higher issue.

### ISSUE THREAD

**Issue by dlehdgud2380** [Black-Seraph/android_patches_gpdwin#5]
I tried GPD Pocket. Working Battery, 3D, 2D,  Bright, Wifi, Bluetooth, Sound...etc. It was so great! But I found bug that cant smooth show 720p60 or higher youtube video.

**Comment by Black-Seraph** [comment]
Known issue, android-x86 doesn't support fully hardware accelerated video playback yet.

As such this is an upstream issue, and one of those things we "need to wait for" instead of implement ourselves. Due to this I've marked the issue as wontfix and closed it for now.

Should it become apparent that android-x86 drops hardware accelerated codecs from their todo list we can re-open this issue.
